apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:njclJcYaYkwCHpjq6FnqH06RwolJrocq8FOzrzLlgaUzEHi7yPcW/hsuztar5a+lqV3yOEHSSp+aMPWsoIVnyK8jIKtTQ4oSnnmT8YciINX6vlG+zyp3u0T7Rhm0EV7eKBQhn0JsRkRk4SLAJZsCfSkMNnkDu2Gqepopl8CjkhdLlak8Tlbb5/9L4srYullRqWk0nGXIWemuS4U66rTv4dgo6GtY1iXxmp5qbU8ZM7nDSOVN3QepJ74qiIdmyWX5mphPdwQ4H0HKFBorNsz7p8xOEk4Jd7CpL4jxi9EsbRL9hgM5X0m2oJXBEGb90GovOloMitsaB2JChOZ/wf73nbzMX7oIF/O6OkUvG4SSZ6Bw+ZaiUoEHgtIb42AakWDV,iv:JqEz+wjTUOe6pzLW785iV8wCcwdd0Xh64naYdknml/s=,tag:pgrhw2d6aoYqHEEf1T2yjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:JNDnwP1uOLuWnHZly279k0OtBrUIBgsdsqmE7lEoqZp6vUQ6QYISBrmAyN9QXN7pluvfRalfyZiJUJGIEmOva7qcfGzGFlzh9YXR252QereqQ9fKgOmMU7RiwoPLfBZmS/HU3cmXtS2QlJ/WjSZkXmZJkkPrM9ZV95HkJeMvKutDPspOVetNEkDiQGzAUv8muMq+5jyJa3X2fw6jPP6WPmGhJ3porAXKmCT5BHVqK/dki2zdTTW1KOZPsh6HeUrvTM5ChfAKCDqv4Veu/Q==,iv:KYgFNWMR8Y4YMfq5TsKlm2KmTt5k6sd71cmIPboc90M=,tag:apJ8u3cSOqSO+7xP9hhBcQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:O6IwPMbfLy8TMW+iALs/78m9eodQMWchjWqWmipa2ntdEDEoj6KiMvhEsrTGDFiaPl2MJmOytivgBVCUGQFqrIaHvq0C21+rjNBscWmU+1mAQUHgfrNy+wkcGgKbHJJQ3TavRj8SidytFg3tUKimhdjeYJj85dUEAsG4ZucFG/QNwdYMLO2xnf9JwfT24bHGYYa8HQkQ7ksWLi9eBJ7H/2wpsjr1YOG4FioTsZ5eUc2tucNpAq7Wsm00tFcCmYRaQoe+4fln2OiQo3wWygT2hZF6ow8=,iv:PEp0mD8i1D8+OaMDDFezQvi0UvHoEA0HklYGr+DZQCg=,tag:s2sNxd6LfgcUCsBuph5aDg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epu2e8qujfqlhgdlh5jwrf0gv2h8jphc7v3n5ym8rcr0jhseseyqzttz0h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVWh2YzNOOEFNQ3FDSmdV
            aDZLcVFaaEV4dG9OMHhqSzN0dmpsSjlVU2hBCmFRRCt5azNEcSsvUjJTYys2TUth
            YmZmN2NHVEM0WlFuZWxRWWJOWW9ldTgKLS0tIDBuanBER0lhcThDWHJiYjB1YUQ0
            RXZ4Z3NBZElzQStkdkphdEIwQU83QjQKI7PIlYi87wLW/cAABKrss8wcmZYkTPWh
            lKcazHFmNNF+YzLjvLEpFnNoWosV4c2wDlDsdFu8jPyxcU/V6xsZEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T17:23:35Z"
    mac: ENC[AES256_GCM,data:RhwXZWowm+mCs4rBYAiJtfb1j1mYdvntII2baJic9Z+xsuNOufsdMaQ+RHKPFXGRgLRgUt8V9Z8FAjE0TDFRY2s1xVtvr7M5p3kkm/5Wi237icgdTUANF+BxM9eWafnHNGv9hWTVZUwwgZC7YRZ7T4Oa9R3yYzzXGFG0DgOr7CQ=,iv:6Jr6+bJ8Tr65JbpYUQjN2OfTb/ufofosSEPBDZc8voQ=,tag:U1aHAgWlHV7xy48NLz1wsQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
